In [1]:
import numpy as np

    ## Numpy Array

In [2]:
list = [1, 2, 3]
list

[1, 2, 3]

In [3]:
type(list)

list

 . . .

In [5]:
array = np.array(list)
array

array([1, 2, 3])

In [6]:
type(array)

numpy.ndarray

. . .

In [7]:
matrix_1 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
matrix_1

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
matrix = np.array(matrix_1)
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
type(matrix)

numpy.ndarray

 Hazır Metotlar

In [12]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
np.arange(0, 101, 2)

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

. . .

In [26]:
matrix_2 = np.arange(0, 60, 5).reshape(4, 3)
matrix_2

array([[ 0,  5, 10],
       [15, 20, 25],
       [30, 35, 40],
       [45, 50, 55]])

. . .

In [27]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [28]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [29]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [30]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

. . .

In [33]:
np.linspace(0, 101, 5)

array([  0.  ,  25.25,  50.5 ,  75.75, 101.  ])

In [34]:
np.linspace(0, 1, 10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

Random

In [35]:
np.random.rand(10)

array([0.72497734, 0.56938334, 0.91146295, 0.00313148, 0.27912016,
       0.40420249, 0.02298004, 0.88458939, 0.16625693, 0.72549673])

In [36]:
np.random.rand(3, 3)

array([[0.19189455, 0.27646519, 0.92771614],
       [0.43317359, 0.90232493, 0.99659512],
       [0.93206096, 0.79622943, 0.69667252]])

NOT : Gaos eğrisi doğrultusunda sayılar üretir ! alt satır . . .

In [37]:
np.random.randn(3, 3)

array([[ 1.0553381 , -0.63960094,  0.3970084 ],
       [ 0.17352409,  0.24621236,  1.71280423],
       [ 1.07110874,  0.20254582, -0.88613115]])

In [52]:
np.random.randint(100)

50

In [59]:
np.random.randint(1, 1000, 4)

array([673, 872, 102, 775])

np.random.seed(?) : Soru işareti yazılan sayı refarans noktasıdır bu noktaya yazılan sayılar ile genel olarak hep aynı sonuçlar üretilir . 

In [66]:
np.random.seed(99)
np.random.rand(4)

array([0.49969432, 0.25593713, 0.25810063, 0.09692171])

Max vs. Min

In [70]:
np.random.seed(99)
random = np.random.randint(0, 101, 10)

random

array([ 1, 35, 57, 40, 73, 82, 68, 69, 52,  1])

In [71]:
random.min()

1

In [72]:
random.max()

82