In [54]:
import numpy as np

Shape & Type

In [55]:
array = np.arange(15) 
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [56]:
array.shape

(15,)

In [57]:
array = array.reshape(1, 15)
array

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]])

In [58]:
array = array.reshape(15, 1)
array

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14]])

In [59]:
array.shape

(15, 1)

In [61]:
array = array.reshape(5, 3)
array

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [62]:
array.dtype

dtype('int32')

İşlem

In [65]:
array_process = np.arange(10, 100, 10).reshape(3, 3)
array_process

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [66]:
array_process + 5

array([[15, 25, 35],
       [45, 55, 65],
       [75, 85, 95]])

In [67]:
array_process - 5

array([[ 5, 15, 25],
       [35, 45, 55],
       [65, 75, 85]])

In [69]:
array_process * 5

array([[ 50, 100, 150],
       [200, 250, 300],
       [350, 400, 450]])

In [70]:
array_process / 5

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.],
       [14., 16., 18.]])

In [72]:
array_process ** 2

array([[ 100,  400,  900],
       [1600, 2500, 3600],
       [4900, 6400, 8100]])

In [73]:
array_process * array_process

array([[ 100,  400,  900],
       [1600, 2500, 3600],
       [4900, 6400, 8100]])

In [75]:
array_process  + 2 * array_process - 4

array([[ 26,  56,  86],
       [116, 146, 176],
       [206, 236, 266]])

In [76]:
np.sqrt(array_process)

array([[3.16227766, 4.47213595, 5.47722558],
       [6.32455532, 7.07106781, 7.74596669],
       [8.36660027, 8.94427191, 9.48683298]])

In [77]:
np.cos(array_process)

array([[-0.83907153,  0.40808206,  0.15425145],
       [-0.66693806,  0.96496603, -0.95241298],
       [ 0.6333192 , -0.11038724, -0.44807362]])

In [78]:
np.tanh(array_process)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [79]:
np.log(array_process)

array([[2.30258509, 2.99573227, 3.40119738],
       [3.68887945, 3.91202301, 4.09434456],
       [4.24849524, 4.38202663, 4.49980967]])

İndex İşlemleri

In [81]:
index_array = np.arange(0, 10)
index_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [82]:
index_array[2:5]

array([2, 3, 4])

In [84]:
index_array[2:5] = 99
index_array

array([ 0,  1, 99, 99, 99,  5,  6,  7,  8,  9])

In [85]:
index_array_part = index_array[2:5]
index_array_part

array([99, 99, 99])